// Palabras dibujables, con onda argentina. Cosas concretas y fáciles de dibujar.
export const WORD_BANK: string[] = [
  // comida y bebida (argenta)
  "mate",
  "termo",
  "bombilla",
  "facturas",
  "medialuna",
  "alfajor",
  "asado",
  "choripán",
  "empanada",
  "milanesa",
  "fernet",
  "parrilla",
  "pava",
  "dulce de leche",
  "tostado",
  "pancho",
  "helado",
  "torta",
  "pizza",
  "fideos",
  "huevo frito",
  "cucurucho",
  "chupetín",
  "caramelo",
  "galletita",
  "queso",
  "banana",
  "manzana",
  "frutilla",
  "sandía",
  "uva",
  "naranja",
  "ananá",
  "zanahoria",
  "morrón",
  "choclo",
  "copa de vino",
  "lata",
  "botella",
  "taza",
  // objetos cotidianos
  "heladera",
  "teléfono",
  "lámpara",
  "silla",
  "cama",
  "puerta",
  "ventana",
  "reloj",
  "llave",
  "candado",
  "tijera",
  "lápiz",
  "pincel",
  "regla",
  "libro",
  "carta",
  "sobre",
  "mochila",
  "valija",
  "paraguas",
  "anteojos",
  "sombrero",
  "gorra",
  "remera",
  "zapatilla",
  "media",
  "guante",
  "campera",
  "bufanda",
  "control remoto",
  "enchufe",
  "foco",
  "vela",
  "espejo",
  "peine",
  "cepillo de dientes",
  "balde",
  "escoba",
  "martillo",
  "destornillador",
  "tornillo",
  "clavo",
  "regalo",
  "globo",
  "cámara de fotos",
  "auricular",
  // transporte
  "colectivo",
  "subte",
  "auto",
  "bici",
  "moto",
  "avión",
  "barco",
  "tren",
  "camión",
  "cohete",
  "helicóptero",
  "semáforo",
  // lugares y construcciones
  "obelisco",
  "casa",
  "iglesia",
  "faro",
  "carpa",
  "puente",
  "escalera",
  "molino",
  "castillo",
  // naturaleza
  "sol",
  "luna",
  "estrella",
  "nube",
  "lluvia",
  "arcoíris",
  "rayo",
  "fuego",
  "árbol",
  "palmera",
  "flor",
  "girasol",
  "cactus",
  "hoja",
  "hongo",
  "montaña",
  "volcán",
  "playa",
  "isla",
  "ola",
  "río",
  "piedra",
  // animales
  "perro",
  "gato",
  "caballo",
  "vaca",
  "chancho",
  "gallina",
  "pollito",
  "oveja",
  "conejo",
  "ratón",
  "pez",
  "pulpo",
  "ballena",
  "tiburón",
  "pingüino",
  "elefante",
  "jirafa",
  "león",
  "mono",
  "oso",
  "tortuga",
  "araña",
  "abeja",
  "mariposa",
  "caracol",
  "hormiga",
  "pájaro",
  "búho",
  "loro",
  "cocodrilo",
  "serpiente",
  "dinosaurio",
  // deportes / juegos / música
  "pelota",
  "cancha",
  "arco",
  "guante de box",
  "raqueta",
  "guitarra",
  "tambor",
  "trompeta",
  "piano",
  "dado",
  "naipe",
  "ajedrez",
  // cuerpo y varios
  "corazón",
  "ojo",
  "mano",
  "pie",
  "oreja",
  "diente",
  "bandera",
  "ancla",
  "brújula",
  "mapa",
  "robot",
  "fantasma",
  "corona",
  "espada",
];

const norm = (w: string) => w.toLowerCase().trim();

/** Devuelve `n` palabras distintas al azar, excluyendo las ya usadas.
 *  Si quedan menos de `n` sin usar, reinicia el ciclo (usa todo el banco). */
export function pickWords(n = 3, exclude: string[] = []): string[] {
  const used = new Set(exclude.map(norm));
  let pool = WORD_BANK.filter((w) => !used.has(norm(w)));
  if (pool.length < n) pool = [...WORD_BANK];
  const out: string[] = [];
  for (let i = 0; i < n && pool.length; i++) {
    const idx = Math.floor(Math.random() * pool.length);
    out.push(pool.splice(idx, 1)[0]);
  }
  return out;
}
