// Palabras dibujables, con onda argentina. Cosas concretas y fáciles de dibujar.
export const WORD_BANK: string[] = [
  "mate",
  "termo",
  "bombilla",
  "facturas",
  "medialuna",
  "alfajor",
  "asado",
  "choripán",
  "empanada",
  "milanesa",
  "fernet",
  "parrilla",
  "pava",
  "heladera",
  "colectivo",
  "subte",
  "obelisco",
  "bandera",
  "pelota",
  "cancha",
  "arco",
  "guitarra",
  "perro",
  "gato",
  "sol",
  "luna",
  "estrella",
  "nube",
  "lluvia",
  "árbol",
  "flor",
  "cactus",
  "casa",
  "auto",
  "bici",
  "moto",
  "avión",
  "barco",
  "corazón",
  "ojo",
  "mano",
  "pie",
  "sombrero",
  "anteojos",
  "reloj",
  "llave",
  "paraguas",
  "globo",
  "torta",
  "helado",
  "pizza",
  "banana",
  "manzana",
  "pescado",
  "pingüino",
  "elefante",
  "tortuga",
  "araña",
  "mariposa",
  "caracol",
  "escalera",
  "puente",
  "montaña",
  "playa",
  "valija",
  "teléfono",
  "lámpara",
  "silla",
  "cama",
  "puerta",
];

/** Devuelve `n` palabras distintas al azar. */
export function pickWords(n = 3): string[] {
  const pool = [...WORD_BANK];
  const out: string[] = [];
  for (let i = 0; i < n && pool.length; i++) {
    const idx = Math.floor(Math.random() * pool.length);
    out.push(pool.splice(idx, 1)[0]);
  }
  return out;
}
